nginx_proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/nginx/certs
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock:ro

lets_encrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: always
  volumes_from:
    - nginx_proxy
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

sop_demo:
  build: .
  ports:
    - "2000:2000"
  environment:
    - HTTPS_METHOD=noredirect
    - VIRTUAL_HOST=example.com,subdomain.example.com
    - LETSENCRYPT_HOST=example.com,subdomain.example.com
    - LETSENCRYPT_EMAIL=<your_email_here@example.com>
